### PR TITLE
Made your code better

### PR DESCRIPTION
**Pull request by TheOnlyWayUp**
Removed all those random variables, made it use asyncio/aiohttp, also uses rich for printing

### CODE REVIEW

**Comment by TheOnlyWayUp** [comment]
forgot to add an image
image

**Comment by TheOnlyWayUp** [comment]
To make it look cleaner, replace the last few lines with
`    for key, value in newStats.items():
        if type(value) is dict:
            print(f"{key}:")
            for key2, value2 in value.items():
                print(f"    {key2} - {value2}")
            print("\n")`

(Just add a print("\n") at the end)

**Comment by AbleToHxck** [comment]
> forgot to add an image image

**Comment by AbleToHxck** [comment]
> Removed all those random variables, made it use asyncio/aiohttp, also uses rich for printing

Hey thanks for improving my code, I'm just a beginner in python, and this was never meant to be an app, it was meant to be a discord bot I was challenged to make one by my friend, after I did I just uploaded the code onto here, but anyways thanks for the help!

**Comment by TheOnlyWayUp** [comment]
> > Removed all those random variables, made it use asyncio/aiohttp, also uses rich for printing
> 
> Hey thanks for improving my code, I'm just a beginner in python, and this was never meant to be an app, it was meant to be a discord bot I was challenged to make one by my friend, after I did I just uploaded the code onto here, but anyways thanks for the help!

Suggest you checkout the code though, you might learn a thing or two from it. once you're done, you can delete the branch.

**Pull request closed without merging**
